### ISSUE TITLE
create_FETE_lcps function

### ISSUE THREAD

**Issue by Kmicaduarte** [josephlewis/leastcostpath#14] opened 2022-12-28 22:55 UTC
I am having trouble with the create_FETE_lcps function. 

The error says: "Error in UseMethod("st_geometry") : 
  no applicable method for 'st_geometry' applied to an object of class "NULL"".

Here is my code:

resRivers <- terra::rast("resRivers2_FLT4S.tif")

#crop to test
e <- ext(c(-80, -71, -5.5, -1.5))
resRiverscut <- crop(resRivers, e)
#resRiverscut[resRiverscut==0] <- 0.0001
plot(resRiverscut)
resRiverscut[is.na(resRiverscut)] <- 10
rm(resRivers)

#Import points

locs <- sf::st_sf(geometry = st_sfc(
  sf::st_point(c(-79.467, -5)),
  sf::st_point(c(-79.093, -4)),
  sf::st_point(c(-79.217, -4)),
  sf::st_point(c(-78.618, -2)),
  sf::st_point(c(-73.834, -5)),
  sf::st_point(c(-71.729, -2)),
  crs = terra::crs(resRiverscut)))

#With leastcostpath package

cs <- create_cs(resRiverscut, max_slope = 5, dem = resRiverscut, neighbours = 4)

lcp_network <- create_FETE_lcps(cs, locations = locs,
                                  cost_distance = TRUE)

**Comment by josephlewis** [comment] 2023-01-02 21:42
Hi @Kmicaduarte 

Without seeing the raster used I can only suggest potential issues:

1) a digital elevation model is required when using max_slope in create_slope. This DEM is used to calculate the slope which is then checked whether it's above the max_slope value. If so, the connection is deemed non-traversable. I'm not sure whether your supplied spatRaster is a DEM or something else?
2) check to see whether all of your points are accessible with your created conductance surface. This can be done via `leastcostpath::check_locations(x = cs, locations = locs)`. Using max_slope = 5 might cause many of these to be inaccessible.

If you're able to share a reproducible example (whether your uploading the raster or by creating dummy data), I can have a deeper look into this.

Thanks for using leastcostpath!

**Comment by josephlewis** [comment] 2023-03-11 19:19
Dear @Kmicaduarte 

This issue is now fixed (see #13).

The problem is with the use of foreach for parallelisation and terra spatVector (spoken about here: https://github.com/rspatial/terra/issues/36).

spatVector can now be used in the create_FETE_lcps() with the error "no applicable method for 'st_geometry' applied to an object of class NULL" now fixed

**Closed as completed** 2023-05-01 16:00 UTC
