### ISSUE TITLE
support for SpatVector or point coordinate inputs

### ISSUE THREAD

**Issue by AMBarbosa** [josephlewis/leastcostpath#13] opened 2022-12-09 12:31 UTC
Hi, thanks for updating the package to work with modern spatial formats! Would you add support also for terra SpatVector inputs, e.g. in `create_lcp()`, `create_cost_corridor()` and other functions that take point inputs? Or at least, support for a numeric vector / matrix / dataframe of point coordinates, not mandatorily a 'sf' object. Cheers!

**Comment by josephlewis** [comment] 2022-12-10 10:53
Hi @AMBarbosa 

Thanks for the issue. Yes, I can do that. I should be able to relax it without too much issue.

I'll work on this when I have time :)

Joe

**Comment by josephlewis** [comment] 2022-12-10 18:33
@AMBarbosa 

Version 2.0.5 should now allow users to supply sf POINT and MULTIPOINT, terra spatVector, data.frame, and matrix objects to origin, destination, and locations arguments (e.g. within create_lcp, create_accum_cost, and create_FETE_lcps)

**Comment by AMBarbosa** [comment] 2023-03-03 10:40
Thanks a bunch! Just one little add: when the input is SpatVector, could the output be (internally converted to) SpatVector as well? Right now, the output is 'sf', which can be confusing for (student) users who are not explicitly using 'sf':
```
r <- terra::rast(system.file("extdata/SICILY_1000m.tif", package="leastcostpath"))
slope_cs <- create_slope_cs(x = r, cost_function = "tobler", neighbours = 4)
locs <- terra::vect(matrix(c(839769, 4199443, 1038608, 4100024, 1017819, 4206255), ncol = 2, byrow = TRUE))
lcp <- create_lcp(x = slope_cs, origin = locs[1,], destination = locs[2:3,], cost_distance = TRUE)

lcp  # sf linestring
vect(lcp)  # SpatVector lines
```

**Comment by josephlewis** [comment] 2023-03-03 10:43
Hi @AMBarbosa 

Can do! Thanks for the suggestion. I'll make sure to add this.

**Comment by lucasbonald** [comment] 2023-03-09 15:13
Hello, Joseph. After the update i'm trying to use shp files as locations points, but i'm facing this issue when calculate the FETE: "no applicable method for 'st_geometry' applied to an object of class NULL".

**Comment by josephlewis** [comment] 2023-03-09 15:19
Hi @lucasbonald are you able to provide the outputs when doing:

`class(your_points)`

it should say 'sf' and 'data.frame'. Hopefully that will help me work out what is going wrong.

As an aside, when I get time to update support for other point coordinate inputs I'll make sure to add a check!

**Comment by lucasbonald** [comment] 2023-03-09 22:26
I got this:
class       : SpatVector 
 geometry    : points 
 dimensions  : 29, 1  (geometries, attributes)
 extent      : 654297.1, 704349.9, 9043604, 9076852  (xmin, xmax, ymin, ymax)
 coord. ref. : +proj=utm +zone=24 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
 names       :    id
 type        : <chr>
 values      :     1
                   2
                   3

**Comment by josephlewis** [comment] 2023-03-09 23:49
Thanks for that @lucasbonald.

The problem is with the use of foreach for parallelisation and terra spatVector (spoken about here: https://github.com/rspatial/terra/issues/36). I've got a fix by packaging the spatVector before sending to foreach but I think I might jig around some things so I don't need to do this.

In the meantime, you can convert your spatVector to sf points via sf::st_as_sf (seen here: https://stackoverflow.com/questions/64035643/converting-spatvector-to-sf-or-sp)

I hope that helps, and thank you for letting me know.

**Comment by josephlewis** [comment] 2023-03-11 18:36
Dear both @AMBarbosa @lucasbonald 

I have fixed the raised issues:

* if spatVector is supplied in locations for create_FETE_lcps() and origin/destination for create_lcp() a spatVector is returned.
*  spatVector can now be used in the create_FETE_lcps() with the error _"no applicable method for 'st_geometry' applied to an object of class NULL"_ now fixed

I'll leave this open for a while. Please can you let me know if you face any issues!

**Comment by lucasbonald** [comment] 2023-03-13 13:09
Thank you very much, @josephlewis. It worked for me now!

**Closed as completed** 2023-05-01 16:00 UTC
